name = "Crusader"
main_cards = [
["22",	"Plains"],
["4",	"Crusade"],
["4",	"Castle"],
["2",	"Disenchant"],
["4",	"White Knight"],
["4",	"Eye for an Eye"],
["2",	"Morale"],
["4",	"Pikemen"],
["4",	"Rainbow Knights"],
["2",	"Battering Ram"],
["2",	"Dancing Scimitar"],
["4",	"Benalish Hero"],
["1",	"Swords to Plowshares"],
]
sideboard_cards = [
["3",	"Swords to Plowshares"],
["2",	"Black Ward"],
["2",	"Blue Ward"],
["2",	"Green Ward"],
["2",	"Red Ward"],
["2",	"White Ward"],
]
walking_sprite = "W_Kht.spr.png"
walking_shadow_sprite = "Skht.spr.png"
face = "MPS_Crusader.png"
level = 3
