name = "Vampire Lord"
main_cards = [
["22",	"Swamp"],
["4",	"Dark Ritual"],
["3",	"Mana Vault"],
["4",	"Animate Dead"],
["4",	"Weakness"],
["4",	"Sengir Vampire"],
["4",	"Sorceress Queen"],
["4",	"Carrion Ants"],
["4",	"Vampire Bats"],
["2",	"Uncle Istvan"],
["2",	"Terror"],
]
sideboard_cards = [
["3",	"Howling Mine"],
["3",	"Black Knight"],
["3",	"Winter Orb"],
]
walking_sprite = "Bk_Lrd.spr.png"
walking_shadow_sprite = "Sb_Lrd.spr.png"
face = "MPS_Vampire_Lord.png"
level = 5
